name: ursim

services:
  ursim:
    build: .
    ports:
      - "29999:29999"
      - "30001:30001"
      - "30002:30002"
      - "30004:30004"
      - "502:502"
      - "6080:6080"
    volumes:
      - ./programs:/ursim/programs
      - ./urcaps:/urcaps
