---
name: Continuous Testing
on:
  pull_request:
    branches:
      - main
  workflow_call:

jobs:
  Continuous_Testing:
    name: Continuous Testing
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v4
      - name: Run Tests
        run: |
          cd examples/simulator
          docker compose up -d
          echo "sleeping for 30 seconds to allow the simulator to start"
          sleep 30
          cargo test --all-features
          docker compose down
