---
name: Continuous Integration
on:
  pull_request:
    branches:
      - main
  workflow_call:

jobs:
  Continuous_Testing:
    name: Continuous Testing
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: cargo build --all-targets --all-features
      - name: Install Docker (MacOS)
        if: runner.os == 'MacOS'
        run: |
          brew install docker compose
      - name: Docker compose up
        run: |
          cd examples/simulator
          docker compose up -d
      - name: Test
        run: cargo test --all-features
      - name: Docker compose down
        run: |
          cd examples/simulator
          docker compose down
